name: slack-postmessage
description: "Call slack-notify's postMessage() with the given arguments"
branding:
  icon: bell
  color: purple
env:
  SLACK_TOKEN:
    description: Slack Bot Token that can write messages to your Slack workspace.
    required: true
inputs:
  message:
    required: true
    description: "Read https://api.slack.com/methods/chat.postMessage for arguments."
outputs: {}
runs:
  using: node12
  main: dist/index.js
