name: 'slack-postmessage'
description: 'Call slack-notify's postMessage() with the given arguments'
branding:
  icon: 'bell'
  color: 'purple'
env:
  SLACK_TOKEN:
    description: 'required'
    required: true
inputs:
  channel:
    required: true
    description: Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name.
  text:
    required: true
    description: How this field works and whether it is required depends on other fields you use in your API call.
  as_user:
    required: false
    description: Pass true to post the message as the authed user, instead of as a bot. Defaults to false. This argument may not be used with newer bot tokens.
  attachments:
    required: false
    description: "A JSON-based array of structured attachments. See https://api.slack.com/messaging/composing/layouts#attachments"
  blocks:
    required: false
    description: A JSON-based array of structured blocks.
  icon_emoji:
    required: false
    description: Emoji to use as the icon for this message. Overrides icon_url. Must be used in conjunction with as_user set to false, otherwise ignored. This argument may not be used with newer bot tokens.
  icon_url:
    required: false
    description: URL to an image to use as the icon for this message. Must be used in conjunction with as_user set to false, otherwise ignored. This argument may not be used with newer bot tokens.
  link_names:
    required: false
    description: Find and link channel names and usernames.
  mrkdwn:
    required: false
    description: Disable Slack markup parsing by setting to false. Enabled by default.
  parse:
    required: false
    description: Change how messages are treated. Defaults to none.
  reply_broadcast:
    required: false
    description: Used in conjunction with thread_ts and indicates whether reply should be made visible to everyone in the channel or conversation. Defaults to false.
  thread_ts:
    required: false
    description: Provide another message's ts value to make this message a reply. Avoid using a reply's ts value; use its parent instead.
  unfurl_links:
    required: false
    description: Pass true to enable unfurling of primarily text-based content.
  unfurl_media:
    required: false
    description: Pass false to disable unfurling of media content.
  username:
    required: false
    description: Set your bot's user name. Must be used in conjunction with as_user set to false, otherwise ignored.
runs:
  using: 'node12'
  main: 'index.js'
